micronaut:
  application:
    name: dataJpaDemo
datasources:
  default:
    url: jdbc:oracle:thin:@barnevents_low?TNS_ADMIN=/wallet
    connectionFactoryClassName: oracle.jdbc.pool.OracleDataSource
    username: testuser
    schema-generate: CREATE_DROP
    dialect: ORACLE
    minPoolSize: 1
    maxPoolSize: 10
jpa:
  default:
    entity-scan:
      packages: 'codes.recursive.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true